### ISSUE TITLE
Changing strip order sometimes not in sync

### ISSUE THREAD

**Issue by brian-slate** [pcww/builder#52]
Noticed I'm seeing ordering issues when dragging strips around. Not sure how exactly to repro, but if you move a couple around quickly drop then, then another quickly it seems fairly easy to "trick" the UI.  Not sure if the virtual board is off, or the ui is off.

**Comment by trezy** [comment]
This issue is caused by our Backbone collection falling out of sync with what's in the UI. There are two things I think will at least help, if not outright fix this bug.
1. Use the Backbone Collection's `splice` method instead of [doing all the heavy lifting in the UI](https://github.com/pcww/builder/blob/master/js/views/Wizard.jsx#L65-L88).
2. Switch over to using a queue. Instead of doing all of the reordering based on the `Sortable` plugin's events -- which I hypothesize may be causing race conditions -- use those events to push changes into a queue that is executed in order. Use `requestAnimationFrame` for executing the changes in the queue.

**Comment by brian-slate** [comment]
Reimplemented dragdrop using react-sortable-hoc. It was painful.
